(ns kotoba.render-shaders
  "Facade re-exporting `kami.render-shaders` (SSoT). ADR-2607102200 addendum 5."
  (:require [kami.render-shaders :as k]))

(def character-U k/character-U)
(def scene-character k/scene-character)
(def scene-voxel k/scene-voxel)
(def scene-particle k/scene-particle)
(def scene-terrain k/scene-terrain)
(def scene-water k/scene-water)
(def scene-sky k/scene-sky)
(def rt-bvh-compute k/rt-bvh-compute)
(def scene-atlas k/scene-atlas)
(def scene-vegetation k/scene-vegetation)
(def mtoon k/mtoon)
(def metahuman-hair k/metahuman-hair)
(def gaussian-splat k/gaussian-splat)
(def strand-compute k/strand-compute)
(def skinned-mtoon k/skinned-mtoon)
(def metahuman-skin k/metahuman-skin)
(def pbr k/pbr)
